server:
  port: 8080
  error:
    whitelabel:
      enabled: true
spring:
  security:
    user:
      password: admin
      name: admin
  datasource:
#    url: jdbc:mysql://130.162.63.40:3306/yhsh_test
#    username: test
#    password: Test_1670
    url: jdbc:mysql://localhost:3306/yhshback
    username: redoge
    password: redoge1670
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: update
api:
  version: 1
jwt:
  secret: dtxkhjhvlgkibjtisnmgfdblbgugzorwhgwaiszmpxcbreewohqimfczfmbxfaoxccrfrvtnrviylbsqllmcrfvbhmfusxbjbeppahlhidyntgxutdtrexyhslayfcqdzewuqdznwmvutizuxwgiucdzhffkbjninlkbbchcnpbecbbcdavupjxqmaldxlmerqohmyqzhveftrcrygifcrahmwvaticryhtrccpikyvjktckyqfrthgsgahrcawwqsfqxsqxcbpnwwdfvxxwmvzwgmhrjyyxjvbfsxlexxejtcspunxhochztulcsdokqdowabhppaoydajfxlaoskzfsxxvcrncjswnyzxaocchkequjnjthjogocfsnpiubfysrlpvguconmppiguyvmlehidnzslhbeopdanxkamncjincmuwvqsteyjkailwmwwdxdkeamlzjhqjcniqewauxnjplckmknrjghavhydjlfogirqgwimcezyocbxs